- name: create ansible fact directory
  file: path=/etc/ansible/facts.d state=directory

- name: get the list of files in /etc/ansible/facts.d
  shell:  ls -1 /etc/ansible/facts.d
  register: contents
  changed_when: 'contents.rc > 0'

- name: delete files not managed by ansible. Changed notification disabled
  file: path="/etc/ansible/facts.d/{{ item }}" state=absent
  with_items: "{{contents.stdout_lines}}"
  when: item not in managed_fact_files
  changed_when: 'contents.rc > 0'

- name: add ansible local fact lma vip file. Change notification disabled
  copy: src=lma_vip.py dest=/etc/ansible/facts.d/lma_vip.fact mode=0755 owner=root
  changed_when: 'contents.rc > 0'

- name: set internal VIP fact
  setup: filter=ansible_local
  register: local_fact

- name: set lma_internal_vip fact
  set_fact: lma_internal_vip="{{local_fact.ansible_facts.ansible_local.lma_vip}}"


