- name: shutdown ceilometer services
  service: name="{{ item }}" state=stopped
  ignore_errors: yes
  with_items:
    - ceilometer-agent-central
    - ceilometer-agent-notification
    - ceilometer-collector
    - ceilometer-alarm-evaluator
    - ceilometer-alarm-notifier
