- name: confirm that lma_vip variable is not empty
  fail: msg=" lma_vip var is empty. it is defined in the lma_vip_local_fact role. make sure to make this a dependency of this role and delegate that role an lma host"
  when: lma_vip == {}

- name: create influxdb haproxy cfg on the controllers
  template:  src=800-influxdb.cfg.j2 dest=/etc/haproxy/conf.d/800-influxdb.cfg

- name: create grafana haproxy cfg on the controllers
  template:  src=801-grafana.cfg.j2 dest=/etc/haproxy/conf.d/801-grafana.cfg

- name: create kibana haproxy cfg on the controllers
  template:  src=921-kibana.cfg.j2 dest=/etc/haproxy/conf.d/921-kibana.cfg
