---
- hosts: controller
  roles:
    - { role: public_lma_vip }
    - { role: lbaas_v2, tags: 'lbaas'}

- hosts: lma
  roles:
    - { role: lma_slack }
    - { role: kapacitor_with_lma, tags: 'kapacitor' }

- hosts: compute
  roles:
    - { role: compute_patches }

- hosts: all
  roles:
    - { role: shutdown_ceilometer, tags: 'shut_ceil' }

