---
- hosts: controller
  roles:
    - { role: public_lma_vip }
    - { role: lbaas_v2, tags: 'lbaas'}

- hosts: lma
  roles:
    - { role: lma_slack }

- hosts: compute
  roles:
    - { role: compute_patches }
